#!/usr/bin/env node
/**
 * Regenerates the geo reference data from `country-state-city` (a devDependency —
 * it is never shipped to a client or loaded by the running API).
 *
 *   node scripts/gen-geo.mjs
 *
 * Writes two things:
 *   • src/countries.generated.ts — every ISO country (name/flag/iso2), ~15 KB,
 *     small enough to ship statically in every bundle.
 *   • ../../apps/api/src/geo/data/cities/<ISO2>.json — city NAMES only, one file
 *     per country. The upstream dataset is a single 8 MB blob; splitting it means
 *     the API reads ~10 KB for a lookup and the clients bundle nothing at all
 *     (they call GET /geo/cities).
 *
 * Re-run after bumping `country-state-city`. Output is committed.
 */
import { mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Country, City } from 'country-state-city';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DATA_DIR = join(ROOT, '..', '..', 'apps', 'api', 'src', 'geo', 'data');
const CITY_DIR = join(DATA_DIR, 'cities');

const countries = Country.getAllCountries().sort((a, b) => a.name.localeCompare(b.name));

/* ── countries ──────────────────────────────────────────────────── */

const rows = countries
  .map((c) => `  { name: ${JSON.stringify(c.name)}, flag: ${JSON.stringify(c.flag ?? '')}, iso2: ${JSON.stringify(c.isoCode)} },`)
  .join('\n');

writeFileSync(
  join(ROOT, 'src', 'countries.generated.ts'),
  `/* eslint-disable */
// GENERATED by scripts/gen-geo.mjs from country-state-city — do not edit by hand.
import type { Country } from './countries';

/** Every ISO 3166-1 country, alphabetical. */
export const ISO_COUNTRIES: Country[] = [
${rows}
];
`,
  'utf8',
);

/* ── cities, one file per country ───────────────────────────────── */

rmSync(CITY_DIR, { recursive: true, force: true });
mkdirSync(CITY_DIR, { recursive: true });

// Name → ISO2 lookup for the API, which resolves the stored country name to a
// city file. Kept as data (not an import of @agrotraders/geo) so the CommonJS
// API never has to depend on an ESM workspace package at runtime. The curated
// names in src/countries.ts are folded in because several of them differ from
// the upstream spelling ("Ivory Coast" vs "Cote D'Ivoire") and they are the ones
// actually persisted.
const codes = Object.fromEntries(countries.map((c) => [c.name.toLowerCase(), c.isoCode]));
const curated = readFileSync(join(ROOT, 'src', 'countries.ts'), 'utf8');
for (const [, name, iso2] of curated.matchAll(/\{ name: '([^']+)',[^}]*iso2: '([A-Z]{2})' \}/g)) {
  codes[name.toLowerCase()] = iso2;
}
writeFileSync(join(DATA_DIR, 'country-codes.json'), JSON.stringify(codes), 'utf8');

let total = 0;
for (const c of countries) {
  const names = Array.from(new Set((City.getCitiesOfCountry(c.isoCode) ?? []).map((x) => x.name))).sort(
    (a, b) => a.localeCompare(b),
  );
  if (!names.length) continue;
  writeFileSync(join(CITY_DIR, `${c.isoCode}.json`), JSON.stringify(names), 'utf8');
  total += names.length;
}

console.log(`geo: ${countries.length} countries, ${total} cities across ${CITY_DIR}`);
