/**
 * Russian labels for service taxonomy nodes, keyed by slug.
 *
 * COMPLETE — every node in `service-taxonomy.json` has a label (699/699), and
 * `service-taxonomy.spec.ts` fails if a new one arrives without one.
 *
 * This file was deliberately partial until 2026-08-25, on the principle that
 * shipping invented Russian is worse than shipping English. In practice that
 * left 434 of 699 names reaching Russian users in English — the whole logistics
 * and processing directory — so the policy was overridden: the gap was filled
 * by Google Translate (en→ru, source pinned; auto-detect 400s a known-source
 * batch) and the machine block below is marked as such.
 *
 * Hand-corrected afterwards where the machine mapped an India-corridor term
 * onto a Russian one: GST came back as НДС, which is a different tax in a
 * different country, and `Cross-Border VAT / GST` became `НДС / НДС`. Acronyms
 * stay Latin — GST, TDS, PF/ESI, E-Way Bill, MIS, SKU, FCL, FEMA.
 *
 * The entries above the machine block are the original hand-curated ones and
 * are the more trustworthy half; prefer correcting the machine block when a
 * native speaker reviews this.
 */
export const SERVICE_TAXONOMY_RU: Record<string, string> = {
  // ── sections ────────────────────────────────────────────────────
  'financial-and-compliance': 'Финансы и соответствие требованиям',
  'logistics-and-handling': 'Логистика и обработка',
  processing: 'Переработка',

  // ── financial & compliance ──────────────────────────────────────
  'financial-and-compliance/accounting': 'Бухгалтерский учёт',
  'financial-and-compliance/accounting/india': 'Индия',
  'financial-and-compliance/accounting/russia': 'Россия',
  'financial-and-compliance/accounting/international': 'Международный / трансграничный',
  'financial-and-compliance/taxation': 'Налогообложение',
  'financial-and-compliance/customs-clearance': 'Таможенное оформление',
  'financial-and-compliance/financial-services': 'Финансовые услуги',
  'financial-and-compliance/audit-and-certification': 'Аудит и сертификация',
  'financial-and-compliance/insurance': 'Страхование',

  // ── logistics & handling ────────────────────────────────────────
  'logistics-and-handling/customs-and-border-logistics': 'Таможенная и приграничная логистика',
  'logistics-and-handling/customs-and-border-logistics/india': 'Индия',
  'logistics-and-handling/customs-and-border-logistics/russia': 'Россия',
  'logistics-and-handling/customs-and-border-logistics/international': 'Международное',
  'logistics-and-handling/fulfilment': 'Фулфилмент',
  'logistics-and-handling/warehousing': 'Складские услуги',
  'logistics-and-handling/packing': 'Упаковка',
  'logistics-and-handling/packing/primary-packing': 'Первичная упаковка',
  'logistics-and-handling/packing/packaging-types': 'Виды упаковки',
  'logistics-and-handling/packing/special-packing': 'Специальная упаковка',
  'logistics-and-handling/packing/packing-support': 'Сопровождение упаковки',
  'logistics-and-handling/transportation': 'Перевозки',
  'logistics-and-handling/transportation/road-transport': 'Автомобильные перевозки',
  'logistics-and-handling/transportation/international-transport': 'Международные перевозки',
  'logistics-and-handling/transportation/shipping-types': 'Типы отправок',
  'logistics-and-handling/transportation/last-mile': 'Последняя миля',
  'logistics-and-handling/freight-forwarding': 'Экспедирование грузов',
  'logistics-and-handling/cold-chain': 'Холодовая цепь',
  'logistics-and-handling/loading-and-unloading': 'Погрузка и разгрузка',
  'logistics-and-handling/container-handling': 'Обработка контейнеров',
  'logistics-and-handling/last-mile-delivery': 'Доставка последней мили',
  'logistics-and-handling/inspection': 'Инспекция',

  // ── processing ──────────────────────────────────────────────────
  'processing/sorting-and-grading': 'Сортировка и калибровка',
  'processing/sorting-and-grading/sorting': 'Сортировка',
  'processing/sorting-and-grading/grading': 'Калибровка',
  'processing/sorting-and-grading/additional': 'Дополнительно',
  'processing/cleaning': 'Очистка',
  'processing/roasting': 'Обжарка',
  'processing/roasting/roasting-types': 'Виды обжарки',
  'processing/roasting/product-specific': 'По продукту',
  'processing/roasting/additional': 'Дополнительно',
  'processing/roasting-and-salting': 'Обжарка и посол',
  'processing/cutting-chopping': 'Резка / измельчение',
  'processing/blanching': 'Бланширование',
  'processing/pitting': 'Удаление косточек',
  'processing/peeling': 'Очистка от кожуры',
  'processing/shelling': 'Лущение / очистка от скорлупы',
  'processing/drying': 'Сушка',
  'processing/freezing-iqf': 'Заморозка / IQF',
  'processing/grinding-and-milling': 'Измельчение и помол',
  'processing/crushing': 'Дробление',
  'processing/mixing-and-blending': 'Смешивание и купажирование',
  'processing/seasoning': 'Приправы и ароматизация',
  'processing/cooking-heat-treatment': 'Варка / термообработка',
  'processing/extraction': 'Экстракция',
  'processing/quality-testing': 'Контроль качества',
  'processing/packaging': 'Фасовка',

  // ── leaves with unambiguous Russian ─────────────────────────────
  // Accounting (shared terms across the three country branches).
  'financial-and-compliance/accounting/india/bookkeeping': 'Ведение бухгалтерского учёта',
  'financial-and-compliance/accounting/russia/bookkeeping': 'Ведение бухгалтерского учёта',
  'financial-and-compliance/accounting/russia/vat-accounting': 'Учёт НДС',
  'financial-and-compliance/accounting/russia/vat-return-preparation': 'Подготовка декларации по НДС',
  'financial-and-compliance/accounting/russia/tax-accounting': 'Налоговый учёт',
  'financial-and-compliance/accounting/russia/payroll-accounting': 'Расчёт заработной платы',
  'financial-and-compliance/accounting/russia/financial-statements': 'Финансовая отчётность',
  'financial-and-compliance/accounting/russia/accounts-payable': 'Кредиторская задолженность',
  'financial-and-compliance/accounting/russia/accounts-receivable': 'Дебиторская задолженность',
  'financial-and-compliance/accounting/russia/bank-reconciliation': 'Банковская сверка',
  'financial-and-compliance/accounting/russia/inventory-accounting': 'Учёт запасов',
  'financial-and-compliance/accounting/russia/fixed-asset-accounting': 'Учёт основных средств',
  'financial-and-compliance/accounting/russia/tax-reporting': 'Налоговая отчётность',
  'financial-and-compliance/accounting/india/payroll-accounting': 'Расчёт заработной платы',
  'financial-and-compliance/accounting/india/bank-reconciliation': 'Банковская сверка',
  'financial-and-compliance/accounting/india/inventory-accounting': 'Учёт запасов',
  'financial-and-compliance/accounting/india/cost-accounting': 'Учёт затрат',
  'financial-and-compliance/accounting/international/ifrs-accounting': 'Учёт по МСФО',
  'financial-and-compliance/accounting/international/payroll-accounting': 'Расчёт заработной платы',
  'financial-and-compliance/accounting/international/accounts-payable': 'Кредиторская задолженность',
  'financial-and-compliance/accounting/international/accounts-receivable': 'Дебиторская задолженность',

  // Warehousing / cold storage — standard trade terms.
  'logistics-and-handling/warehousing/general-warehousing': 'Общее складское хранение',
  'logistics-and-handling/warehousing/cold-storage': 'Холодильное хранение',
  'logistics-and-handling/warehousing/frozen-storage': 'Хранение в морозильной камере',
  'logistics-and-handling/warehousing/chilled-storage': 'Охлаждаемое хранение',
  'logistics-and-handling/warehousing/ambient-storage': 'Хранение при температуре окружающей среды',
  'logistics-and-handling/warehousing/bonded-warehousing': 'Таможенный склад',
  'logistics-and-handling/warehousing/bulk-storage': 'Хранение навалом',
  'logistics-and-handling/warehousing/pallet-storage': 'Паллетное хранение',
  'logistics-and-handling/warehousing/container-storage': 'Хранение контейнеров',
  'logistics-and-handling/warehousing/long-term-storage': 'Долгосрочное хранение',
  'logistics-and-handling/warehousing/temporary-storage': 'Временное хранение',

  // Transport / freight.
  'logistics-and-handling/transportation/road-transport/local-transport': 'Местные перевозки',
  'logistics-and-handling/transportation/road-transport/intercity-transport': 'Междугородние перевозки',
  'logistics-and-handling/transportation/road-transport/container-transport': 'Контейнерные перевозки',
  'logistics-and-handling/transportation/international-transport/air-freight': 'Авиаперевозки',
  'logistics-and-handling/transportation/international-transport/sea-freight': 'Морские перевозки',
  'logistics-and-handling/transportation/international-transport/rail-freight': 'Железнодорожные перевозки',
  'logistics-and-handling/transportation/international-transport/multimodal-transport': 'Мультимодальные перевозки',
  'logistics-and-handling/transportation/last-mile/last-mile-delivery': 'Доставка последней мили',
  'logistics-and-handling/transportation/last-mile/express-delivery': 'Экспресс-доставка',

  // Customs.
  'logistics-and-handling/customs-and-border-logistics/import-customs-clearance': 'Таможенное оформление импорта',
  'logistics-and-handling/customs-and-border-logistics/export-customs-clearance': 'Таможенное оформление экспорта',
  'logistics-and-handling/customs-and-border-logistics/customs-documentation': 'Таможенная документация',
  'logistics-and-handling/customs-and-border-logistics/customs-brokerage': 'Услуги таможенного брокера',
  'logistics-and-handling/customs-and-border-logistics/import-documentation': 'Импортная документация',
  'logistics-and-handling/customs-and-border-logistics/export-documentation': 'Экспортная документация',
  'logistics-and-handling/customs-and-border-logistics/russia/russian-customs': 'Российская таможня',
  'logistics-and-handling/customs-and-border-logistics/india/indian-customs': 'Индийская таможня',

  // Processing leaves.
  'processing/sorting-and-grading/sorting/manual-sorting': 'Ручная сортировка',
  'processing/sorting-and-grading/sorting/machine-sorting': 'Машинная сортировка',
  'processing/sorting-and-grading/sorting/optical-sorting': 'Оптическая сортировка',
  'processing/sorting-and-grading/sorting/colour-sorting': 'Сортировка по цвету',
  'processing/sorting-and-grading/sorting/size-sorting': 'Сортировка по размеру',
  'processing/sorting-and-grading/sorting/weight-sorting': 'Сортировка по весу',
  'processing/sorting-and-grading/grading/quality-grading': 'Калибровка по качеству',
  'processing/sorting-and-grading/grading/size-grading': 'Калибровка по размеру',
  'processing/sorting-and-grading/grading/moisture-grading': 'Калибровка по влажности',
  'processing/cleaning/dry-cleaning': 'Сухая очистка',
  'processing/cleaning/wet-cleaning': 'Влажная очистка',
  'processing/cleaning/water-washing': 'Промывка водой',
  'processing/cleaning/steam-cleaning': 'Паровая очистка',
  'processing/cleaning/dust-removal': 'Удаление пыли',
  'processing/roasting/roasting-types/dry-roasting': 'Сухая обжарка',
  'processing/roasting/roasting-types/oil-roasting': 'Обжарка в масле',
  'processing/roasting/roasting-types/hot-air-roasting': 'Обжарка горячим воздухом',
  'processing/roasting/roasting-types/drum-roasting': 'Барабанная обжарка',
  'processing/roasting/roasting-types/batch-roasting': 'Партионная обжарка',
  'processing/roasting/roasting-types/light-roasting': 'Светлая обжарка',
  'processing/roasting/roasting-types/medium-roasting': 'Средняя обжарка',
  'processing/roasting/roasting-types/dark-roasting': 'Тёмная обжарка',
  'processing/roasting/product-specific/nut-roasting': 'Обжарка орехов',
  'processing/roasting/product-specific/coffee-roasting': 'Обжарка кофе',
  'processing/roasting/product-specific/almond-roasting': 'Обжарка миндаля',
  'processing/roasting/product-specific/peanut-roasting': 'Обжарка арахиса',
  'processing/roasting/product-specific/spice-roasting': 'Обжарка специй',
  'processing/cutting-chopping/hand-cutting': 'Ручная резка',
  'processing/cutting-chopping/machine-cutting': 'Машинная резка',
  'processing/cutting-chopping/slicing': 'Нарезка ломтиками',
  'processing/cutting-chopping/dicing': 'Нарезка кубиками',
  'processing/cutting-chopping/shredding': 'Шинковка',
  'processing/cutting-chopping/halving': 'Разрезание пополам',
  'processing/blanching/water-blanching': 'Бланширование в воде',
  'processing/blanching/steam-blanching': 'Бланширование паром',
  'processing/peeling/manual-peeling': 'Ручная очистка',
  'processing/peeling/mechanical-peeling': 'Механическая очистка',
  'processing/peeling/steam-peeling': 'Паровая очистка',
  'processing/drying/sun-drying': 'Солнечная сушка',
  'processing/drying/solar-drying': 'Гелиосушка',
  'processing/drying/hot-air-drying': 'Сушка горячим воздухом',
  'processing/drying/vacuum-drying': 'Вакуумная сушка',
  'processing/drying/freeze-drying': 'Сублимационная сушка',
  'processing/drying/spray-drying': 'Распылительная сушка',
  'processing/freezing-iqf/blast-freezing': 'Шоковая заморозка',
  'processing/freezing-iqf/cryogenic-freezing': 'Криогенная заморозка',
  'processing/freezing-iqf/thawing': 'Размораживание',
  'processing/grinding-and-milling/fine-grinding': 'Тонкий помол',
  'processing/grinding-and-milling/coarse-grinding': 'Крупный помол',
  'processing/grinding-and-milling/flour-milling': 'Мукомольное производство',
  'processing/grinding-and-milling/spice-grinding': 'Помол специй',
  'processing/grinding-and-milling/coffee-grinding': 'Помол кофе',
  'processing/mixing-and-blending/dry-blending': 'Сухое смешивание',
  'processing/mixing-and-blending/spice-blending': 'Купажирование специй',
  'processing/mixing-and-blending/tea-blending': 'Купажирование чая',
  'processing/mixing-and-blending/coffee-blending': 'Купажирование кофе',
  'processing/cooking-heat-treatment/boiling': 'Варка',
  'processing/cooking-heat-treatment/steaming': 'Приготовление на пару',
  'processing/cooking-heat-treatment/baking': 'Выпекание',
  'processing/cooking-heat-treatment/frying': 'Жарка',
  'processing/cooking-heat-treatment/pasteurisation': 'Пастеризация',
  'processing/cooking-heat-treatment/sterilisation': 'Стерилизация',
  'processing/extraction/juice-extraction': 'Отжим сока',
  'processing/extraction/oil-extraction': 'Извлечение масла',
  'processing/extraction/cold-pressing': 'Холодный отжим',
  'processing/extraction/hot-pressing': 'Горячий отжим',
  'processing/extraction/filtering': 'Фильтрация',
  'processing/quality-testing/quality-inspection': 'Инспекция качества',
  'processing/quality-testing/moisture-testing': 'Определение влажности',
  'processing/quality-testing/metal-detection': 'Металлодетекция',
  'processing/quality-testing/x-ray-inspection': 'Рентген-контроль',
  'processing/quality-testing/microbiological-testing': 'Микробиологические исследования',
  'processing/quality-testing/pre-shipment-inspection': 'Предотгрузочная инспекция',

  // legal
  'financial-and-compliance/legal': 'Юридические услуги',
  'financial-and-compliance/legal/india': 'Индия',
  'financial-and-compliance/legal/russia': 'Россия',
  'financial-and-compliance/legal/international': 'Международный / трансграничный',
  'financial-and-compliance/legal/india/sale-and-purchase-agreement-drafting': 'Составление договора купли-продажи',
  'financial-and-compliance/legal/india/contract-review-and-vetting': 'Правовая экспертиза договоров',
  'financial-and-compliance/legal/india/agency-and-distribution-agreements': 'Агентские и дистрибьюторские договоры',
  'financial-and-compliance/legal/india/non-disclosure-agreements': 'Соглашения о неразглашении (NDA)',
  'financial-and-compliance/legal/india/company-incorporation': 'Регистрация компании',
  'financial-and-compliance/legal/india/foreign-subsidiary-setup': 'Создание дочерней компании',
  'financial-and-compliance/legal/india/shareholder-and-joint-venture-agreements': 'Акционерные соглашения и договоры о СП',
  'financial-and-compliance/legal/india/trademark-search-and-filing': 'Поиск и регистрация товарного знака',
  'financial-and-compliance/legal/india/trademark-opposition': 'Возражения против регистрации товарного знака',
  'financial-and-compliance/legal/india/geographical-indication-registration': 'Регистрация географического указания',
  'financial-and-compliance/legal/india/copyright-registration': 'Регистрация авторских прав',
  'financial-and-compliance/legal/india/anti-dumping-and-trade-remedy-advisory': 'Антидемпинговые меры и защита рынка',
  'financial-and-compliance/legal/india/commercial-arbitration': 'Коммерческий арбитраж',
  'financial-and-compliance/legal/india/debt-recovery-and-demand-notices': 'Взыскание задолженности и претензии',
  'financial-and-compliance/legal/india/commercial-litigation': 'Коммерческие судебные споры',
  'financial-and-compliance/legal/india/agricultural-land-due-diligence': 'Проверка сельскохозяйственных земель',
  'financial-and-compliance/legal/india/warehouse-and-cold-store-lease-drafting': 'Договоры аренды склада и холодильника',
  'financial-and-compliance/legal/india/employment-and-contractor-agreements': 'Трудовые и подрядные договоры',
  'financial-and-compliance/legal/india/labour-law-compliance': 'Соблюдение трудового законодательства',
  'financial-and-compliance/legal/india/legal-due-diligence': 'Юридический due diligence',
  'financial-and-compliance/legal/india/power-of-attorney-drafting': 'Составление доверенности',
  'financial-and-compliance/legal/india/apostille-and-document-legalisation': 'Апостиль и легализация документов',
  'financial-and-compliance/legal/india/cargo-insurance-claim-support': 'Сопровождение страховых требований по грузу',
  'financial-and-compliance/legal/russia/supply-contract-drafting': 'Составление договора поставки',
  'financial-and-compliance/legal/russia/contract-review-and-vetting': 'Правовая экспертиза договоров',
  'financial-and-compliance/legal/russia/agency-and-distribution-agreements': 'Агентские и дистрибьюторские договоры',
  'financial-and-compliance/legal/russia/non-disclosure-agreements': 'Соглашения о неразглашении (NDA)',
  'financial-and-compliance/legal/russia/ooo-company-registration': 'Регистрация ООО',
  'financial-and-compliance/legal/russia/individual-entrepreneur-registration': 'Регистрация ИП',
  'financial-and-compliance/legal/russia/representative-office-setup': 'Открытие представительства',
  'financial-and-compliance/legal/russia/charter-and-participant-agreements': 'Устав и договоры участников',
  'financial-and-compliance/legal/russia/egrul-changes-and-filings': 'Внесение изменений в ЕГРЮЛ',
  'financial-and-compliance/legal/russia/rosselkhoznadzor-compliance-advisory': 'Сопровождение требований Россельхознадзора',
  'financial-and-compliance/legal/russia/eaeu-technical-regulation-compliance': 'Соответствие техрегламентам ЕАЭС',
  'financial-and-compliance/legal/russia/declaration-of-conformity-support': 'Оформление декларации о соответствии',
  'financial-and-compliance/legal/russia/trademark-registration-rospatent': 'Регистрация товарного знака (Роспатент)',
  'financial-and-compliance/legal/russia/currency-control-and-repatriation-advisory': 'Валютный контроль и репатриация выручки',
  'financial-and-compliance/legal/russia/customs-classification-opinion-tn-ved': 'Классификация товара по ТН ВЭД',
  'financial-and-compliance/legal/russia/customs-dispute-representation': 'Споры с таможенными органами',
  'financial-and-compliance/legal/russia/sanctions-and-export-control-screening': 'Проверка на санкции и экспортный контроль',
  'financial-and-compliance/legal/russia/arbitrazh-court-representation': 'Представительство в арбитражном суде',
  'financial-and-compliance/legal/russia/commercial-arbitration': 'Коммерческий арбитраж',
  'financial-and-compliance/legal/russia/debt-recovery-and-claim-letters': 'Взыскание задолженности и претензии',
  'financial-and-compliance/legal/russia/bankruptcy-and-insolvency-advisory': 'Банкротство и несостоятельность',
  'financial-and-compliance/legal/russia/land-and-warehouse-lease-drafting': 'Договоры аренды земли и склада',
  'financial-and-compliance/legal/russia/agricultural-land-due-diligence': 'Проверка сельскохозяйственных земель',
  'financial-and-compliance/legal/russia/employment-contracts-and-hr-documents': 'Трудовые договоры и кадровые документы',
  'financial-and-compliance/legal/russia/migrant-worker-documentation': 'Оформление иностранных работников',
  'financial-and-compliance/legal/russia/personal-data-152-fz-compliance': 'Соответствие 152-ФЗ о персональных данных',
  'financial-and-compliance/legal/russia/legal-due-diligence': 'Юридический due diligence',
  'financial-and-compliance/legal/russia/notarisation-and-apostille-support': 'Нотариальное заверение и апостиль',
  'financial-and-compliance/legal/russia/cargo-insurance-claim-support': 'Сопровождение страховых требований по грузу',
  'financial-and-compliance/legal/international/international-sale-contract-drafting': 'Составление международного договора купли-продажи',
  'financial-and-compliance/legal/international/gafta-contract-advisory': 'Консультации по контрактам GAFTA',
  'financial-and-compliance/legal/international/fosfa-contract-advisory': 'Консультации по контрактам FOSFA',
  'financial-and-compliance/legal/international/incoterms-advisory': 'Консультации по Инкотермс',
  'financial-and-compliance/legal/international/cross-border-distribution-and-agency-agreements': 'Трансграничные дистрибьюторские и агентские договоры',
  'financial-and-compliance/legal/international/letter-of-credit-and-ucp-600-advisory': 'Аккредитивы и UCP 600',
  'financial-and-compliance/legal/international/trade-finance-documentation-review': 'Экспертиза документов торгового финансирования',
  'financial-and-compliance/legal/international/sanctions-and-export-control-screening': 'Проверка на санкции и экспортный контроль',
  'financial-and-compliance/legal/international/cross-border-due-diligence': 'Трансграничный due diligence',
  'financial-and-compliance/legal/international/gafta-arbitration-representation': 'Представительство в арбитраже GAFTA',
  'financial-and-compliance/legal/international/icc-arbitration-representation': 'Представительство в арбитраже ICC',
  'financial-and-compliance/legal/international/international-mediation': 'Международная медиация',
  'financial-and-compliance/legal/international/enforcement-of-foreign-awards': 'Признание и исполнение иностранных решений',
  'financial-and-compliance/legal/international/cross-border-debt-recovery': 'Трансграничное взыскание задолженности',
  'financial-and-compliance/legal/international/international-trademark-filing-madrid-protocol': 'Международная регистрация товарного знака (Мадридская система)',
  'financial-and-compliance/legal/international/phytosanitary-and-quarantine-legal-support': 'Правовое сопровождение фитосанитарии и карантина',
  'financial-and-compliance/legal/international/organic-certification-legal-support': 'Правовое сопровождение органической сертификации',
  'financial-and-compliance/legal/international/halal-and-kosher-certification-legal-support': 'Правовое сопровождение сертификации халяль и кошер',
  'financial-and-compliance/legal/international/food-labelling-compliance-review': 'Проверка маркировки пищевой продукции',
  'financial-and-compliance/legal/international/product-liability-and-recall-advisory': 'Ответственность за продукцию и отзыв товара',
  'financial-and-compliance/legal/international/marine-cargo-claim-support': 'Морские грузовые претензии',
  'financial-and-compliance/legal/international/charterparty-and-bill-of-lading-advisory': 'Чартер и коносамент',
  'financial-and-compliance/legal/international/joint-venture-structuring': 'Структурирование совместных предприятий',
  'financial-and-compliance/legal/international/cross-border-tax-structuring-advisory': 'Трансграничное налоговое структурирование',
  'financial-and-compliance/legal/international/data-protection-gdpr-advisory': 'Защита персональных данных (GDPR)',
  'financial-and-compliance/legal/international/legal-retainer-ongoing-advisory': 'Абонентское юридическое обслуживание',
  'financial-and-compliance/legal/international/apostille-and-document-legalisation': 'Апостиль и легализация документов',
  'financial-and-compliance/legal/international/notarisation-support': 'Нотариальное сопровождение',

  /* ── Machine-translated 2026-08-25 ──────────────────────────────────
   * Google Translate (en→ru), then hand-corrected where it mapped an
   * India-corridor term onto a Russian one — GST is not НДС, and
   * `Cross-Border VAT / GST` came back as `НДС / НДС`. Acronyms kept
   * Latin per the policy above. Flagged for native-speaker review:
   * these are machine output, not confident trade terms.
   */
  'financial-and-compliance/accounting/india/gst-registration': 'Регистрация GST',
  'financial-and-compliance/accounting/india/gst-return-filing': 'Подача деклараций GST',
  'financial-and-compliance/accounting/india/gst-reconciliation': 'Сверка GST',
  'financial-and-compliance/accounting/india/gst-advisory': 'Консультации по GST',
  'financial-and-compliance/accounting/india/e-invoicing-support': 'Поддержка электронного выставления счетов',
  'financial-and-compliance/accounting/india/e-way-bill-support': 'Поддержка E-Way Bill',
  'financial-and-compliance/accounting/india/income-tax-return-filing': 'Подача налоговой декларации',
  'financial-and-compliance/accounting/india/tds-compliance-and-returns': 'Соблюдение требований TDS и возврат средств',
  'financial-and-compliance/accounting/india/tax-audit-support': 'Поддержка при налоговых проверках',
  'financial-and-compliance/accounting/india/financial-statement-preparation': 'Подготовка финансовой отчетности',
  'financial-and-compliance/accounting/india/balance-sheet-and-p-and-l-preparation': 'Составление баланса и отчета о прибылях и убытках',
  'financial-and-compliance/accounting/india/accounts-payable-management': 'Управление дебиторской и кредиторской задолженностью',
  'financial-and-compliance/accounting/india/accounts-receivable-management': 'Управление дебиторской задолженностью',
  'financial-and-compliance/accounting/india/professional-tax-compliance': 'Профессиональное соблюдение налогового законодательства',
  'financial-and-compliance/accounting/india/pf-esi-accounting-support': 'Поддержка в ведении бухгалтерского учета PF/ESI',
  'financial-and-compliance/accounting/india/management-accounting-mis': 'Управленческий учёт / MIS',
  'financial-and-compliance/accounting/india/cash-flow-reporting': 'Отчетность о движении денежных средств',
  'financial-and-compliance/accounting/india/virtual-cfo-services': 'Услуги виртуального финансового директора',
  'financial-and-compliance/accounting/india/company-accounting': 'Бухгалтерский учет компании',
  'financial-and-compliance/accounting/india/startup-accounting': 'Бухгалтерский учет для стартапов',
  'financial-and-compliance/accounting/india/import-export-accounting': 'Учет импорта/экспорта',
  'financial-and-compliance/accounting/india/foreign-currency-accounting': 'Учет иностранной валюты',
  'financial-and-compliance/accounting/india/audit-preparation-and-support': 'Подготовка к аудиту и поддержка',
  'financial-and-compliance/accounting/russia/russian-statutory-accounting': 'Российский нормативный бухгалтерский учет',
  'financial-and-compliance/accounting/russia/corporate-profit-tax-support': 'Поддержка по вопросам корпоративного/прибыльного налогообложения',
  'financial-and-compliance/accounting/russia/employee-tax-accounting': 'Учет налогов сотрудников',
  'financial-and-compliance/accounting/russia/expense-accounting': 'Учет расходов',
  'financial-and-compliance/accounting/russia/management-reporting': 'Управленческая отчетность',
  'financial-and-compliance/accounting/russia/cash-flow-reporting': 'Отчетность о движении денежных средств',
  'financial-and-compliance/accounting/russia/electronic-document-accounting': 'Электронный документооборот',
  'financial-and-compliance/accounting/russia/invoice-accounting': 'Учет счетов-фактур',
  'financial-and-compliance/accounting/russia/simplified-tax-regime-support': 'Поддержка упрощенного налогового режима',
  'financial-and-compliance/accounting/russia/foreign-company-accounting': 'Бухгалтерский учет иностранной компании',
  'financial-and-compliance/accounting/russia/cross-border-transaction-accounting': 'Учет трансграничных транзакций',
  'financial-and-compliance/accounting/russia/import-export-accounting': 'Учет импорта/экспорта',
  'financial-and-compliance/accounting/russia/foreign-currency-accounting': 'Учет иностранной валюты',
  'financial-and-compliance/accounting/russia/tax-authority-reconciliation': 'Сверка налоговых данных',
  'financial-and-compliance/accounting/russia/accounting-cleanup-backlog-accounting': 'Упорядочение бухгалтерского учета / Бухгалтерская задолженность',
  'financial-and-compliance/accounting/russia/virtual-accountant-outsourced-accounting': 'Виртуальный бухгалтер / Бухгалтерский аутсорсинг',
  'financial-and-compliance/accounting/international/international-bookkeeping': 'Международный бухгалтерский учет',
  'financial-and-compliance/accounting/international/multi-country-accounting': 'Многострановый учет',
  'financial-and-compliance/accounting/international/consolidated-financial-statements': 'Консолидированная финансовая отчетность',
  'financial-and-compliance/accounting/international/management-reporting': 'Управленческая отчетность',
  'financial-and-compliance/accounting/international/group-company-accounting': 'Бухгалтерский учет группы компаний',
  'financial-and-compliance/accounting/international/multi-currency-accounting': 'Многовалютный учет',
  'financial-and-compliance/accounting/international/intercompany-accounting': 'Внутригрупповой учет',
  'financial-and-compliance/accounting/international/international-vat-gst-support': 'Международная поддержка по НДС/GST',
  'financial-and-compliance/accounting/international/vat-gst-registration-support': 'Поддержка при регистрации НДС/GST',
  'financial-and-compliance/accounting/international/cross-border-vat-gst': 'Трансграничный НДС / GST',
  'financial-and-compliance/accounting/international/import-export-accounting': 'Учет импорта/экспорта',
  'financial-and-compliance/accounting/international/customs-accounting': 'Таможенный учет',
  'financial-and-compliance/accounting/international/transfer-pricing-support': 'Поддержка трансфертного ценообразования',
  'financial-and-compliance/accounting/international/intercompany-reconciliation': 'Внутрифирменная сверка',
  'financial-and-compliance/accounting/international/international-tax-accounting': 'Международный налоговый учет',
  'financial-and-compliance/accounting/international/withholding-tax-support': 'Поддержка по удержанию налога',
  'financial-and-compliance/accounting/international/double-taxation-documentation-support': 'Поддержка в оформлении документов по двойному налогообложению',
  'financial-and-compliance/accounting/international/permanent-establishment-accounting-support': 'Поддержка бухгалтерского учета постоянного представительства',
  'financial-and-compliance/accounting/international/foreign-subsidiary-accounting': 'Учет иностранных дочерних компаний',
  'financial-and-compliance/accounting/international/branch-accounting': 'Учет филиалов',
  'financial-and-compliance/accounting/international/marketplace-e-commerce-accounting': 'Бухгалтерский учет для маркетплейсов / электронной коммерции',
  'financial-and-compliance/accounting/international/international-seller-accounting': 'Международный учет продавцов',
  'financial-and-compliance/accounting/international/cross-border-e-commerce-accounting': 'Бухгалтерский учет трансграничной электронной коммерции',
  'financial-and-compliance/accounting/international/saas-digital-services-accounting': 'Бухгалтерский учет SaaS / цифровых услуг',
  'financial-and-compliance/accounting/international/royalty-accounting': 'Учет роялти',
  'financial-and-compliance/accounting/international/international-invoice-management': 'Международное управление счетами-фактурами',
  'financial-and-compliance/accounting/international/foreign-exchange-reconciliation': 'Сверка валютных курсов',
  'financial-and-compliance/accounting/international/consolidation-and-group-reporting': 'Консолидация и групповая отчетность',
  'financial-and-compliance/accounting/international/audit-support': 'Поддержка аудита',
  'financial-and-compliance/accounting/international/virtual-cfo': 'Виртуальный финансовый директор',
  'financial-and-compliance/accounting/international/outsourced-finance-department': 'Аутсорсинговый финансовый отдел',
  'financial-and-compliance/legal/india/llp-registration': 'Регистрация товарищества с ограниченной ответственностью',
  'financial-and-compliance/legal/india/roc-annual-filings': 'Ежегодная отчетность Регистратора компаний',
  'financial-and-compliance/legal/india/fssai-licence-registration': 'Регистрация лицензии FSSAI',
  'financial-and-compliance/legal/india/apeda-registration': 'Регистрация в APEDA',
  'financial-and-compliance/legal/india/import-export-code-iec-registration': 'Регистрация кода импорта/экспорта (IEC)',
  'financial-and-compliance/legal/india/legal-metrology-registration': 'Регистрация в области правовой метрологии',
  'financial-and-compliance/legal/india/fema-and-foreign-exchange-advisory': 'Консультации по FEMA и валютному регулированию',
  'financial-and-compliance/legal/india/customs-classification-opinion-hs-code': 'Классификационное заключение таможни (код ТН ВЭД)',
  'financial-and-compliance/legal/india/customs-and-dgft-dispute-representation': 'Представление интересов в спорах с Таможенной службой и Генеральным директоратом внешней торговли',
  'financial-and-compliance/legal/india/cheque-dishonour-section-138-cases': 'Дела о неплатежеспособности чеков (статья 138)',
  'financial-and-compliance/legal/india/posh-policy-and-compliance': 'Политика и соблюдение требований по предотвращению сексуальных домогательств на рабочем месте (POSH).',
  'financial-and-compliance/legal/india/notarisation-and-affidavits': 'Нотариальное заверение и аффидавиты',
  'logistics-and-handling/customs-and-border-logistics/india/port-handling': 'Портовое обслуживание',
  'logistics-and-handling/customs-and-border-logistics/india/icd-handling': 'Обращение с имплантируемым кардиодефибриллятором',
  'logistics-and-handling/customs-and-border-logistics/india/cfs-handling': 'Обработка CFS',
  'logistics-and-handling/customs-and-border-logistics/india/gst-related-logistics-documentation': 'Логистическая документация по GST',
  'logistics-and-handling/customs-and-border-logistics/india/e-way-bill-support': 'Поддержка E-Way Bill',
  'logistics-and-handling/customs-and-border-logistics/india/export-documentation': 'Экспорт документации',
  'logistics-and-handling/customs-and-border-logistics/russia/eurasian-economic-union-eaeu-related-support': 'Евразийский экономический союз / поддержка, связанная с ЕАЭС',
  'logistics-and-handling/customs-and-border-logistics/russia/import-documentation': 'Импорт документации',
  'logistics-and-handling/customs-and-border-logistics/russia/export-documentation': 'Экспорт документации',
  'logistics-and-handling/customs-and-border-logistics/russia/border-logistics': 'Пограничная логистика',
  'logistics-and-handling/customs-and-border-logistics/russia/customs-warehouse-handling': 'Таможенное складское хранение',
  'logistics-and-handling/customs-and-border-logistics/international/cross-border-customs': 'Трансграничная таможня',
  'logistics-and-handling/customs-and-border-logistics/international/import-export-documentation': 'Документация по импорту/экспорту',
  'logistics-and-handling/customs-and-border-logistics/international/multimodal-freight': 'Мультимодальные грузоперевозки',
  'logistics-and-handling/customs-and-border-logistics/international/international-freight-forwarding': 'Международные грузоперевозки',
  'logistics-and-handling/customs-and-border-logistics/hs-code-assistance': 'Помощь по коду ТН ВЭД',
  'logistics-and-handling/customs-and-border-logistics/duty-calculation-assistance': 'Помощь в расчете таможенных пошлин',
  'logistics-and-handling/customs-and-border-logistics/certificate-documentation': 'Документация по сертификату',
  'logistics-and-handling/customs-and-border-logistics/country-of-origin-documentation': 'Документация о стране происхождения',
  'logistics-and-handling/customs-and-border-logistics/bill-of-entry-support': 'Поддержка при оформлении таможенной декларации',
  'logistics-and-handling/customs-and-border-logistics/shipping-bill-support': 'Поддержка по вопросам доставки и выставления счетов',
  'logistics-and-handling/customs-and-border-logistics/transit-documentation': 'Транспортная документация',
  'logistics-and-handling/customs-and-border-logistics/customs-inspection-coordination': 'Координация таможенного досмотра',
  'logistics-and-handling/customs-and-border-logistics/port-clearance': 'Портовое оформление',
  'logistics-and-handling/customs-and-border-logistics/airport-clearance': 'Прохождение контроля в аэропорту',
  'logistics-and-handling/customs-and-border-logistics/border-clearance': 'Прохождение пограничного контроля',
  'logistics-and-handling/customs-and-border-logistics/temporary-import-handling': 'Временная обработка импортных грузов',
  'logistics-and-handling/customs-and-border-logistics/re-export-handling': 'Обработка реэкспортных операций',
  'logistics-and-handling/customs-and-border-logistics/bonded-cargo-handling': 'Обработка грузов под таможенным контролем',
  'logistics-and-handling/fulfilment/order-fulfilment': 'Выполнение заказов',
  'logistics-and-handling/fulfilment/b2b-fulfilment': 'B2B-выполнение заказов',
  'logistics-and-handling/fulfilment/b2c-fulfilment': 'Выполнение заказов B2C',
  'logistics-and-handling/fulfilment/e-commerce-fulfilment': 'Выполнение заказов в электронной коммерции',
  'logistics-and-handling/fulfilment/marketplace-fulfilment': 'Выполнение заказов на торговой площадке',
  'logistics-and-handling/fulfilment/amazon-flipkart-ozon-wildberries-fulfilment': 'Фулфилмент Amazon / Flipkart / Ozon / Wildberries',
  'logistics-and-handling/fulfilment/pick-and-pack': 'Комплектация и упаковка',
  'logistics-and-handling/fulfilment/order-processing': 'Обработка заказов',
  'logistics-and-handling/fulfilment/inventory-storage': 'Хранение запасов',
  'logistics-and-handling/fulfilment/inventory-management': 'Управление запасами',
  'logistics-and-handling/fulfilment/warehouse-management': 'Управление складом',
  'logistics-and-handling/fulfilment/receiving-and-inbound-handling': 'Приём и обработка входящих товаров',
  'logistics-and-handling/fulfilment/outbound-handling': 'Обработка исходящих отправлений',
  'logistics-and-handling/fulfilment/dispatch-management': 'Управление диспетчеризацией',
  'logistics-and-handling/fulfilment/same-day-dispatch': 'Отправка в тот же день',
  'logistics-and-handling/fulfilment/next-day-dispatch': 'Отправка на следующий день',
  'logistics-and-handling/fulfilment/cross-docking': 'Кросс-докинг',
  'logistics-and-handling/fulfilment/palletisation': 'Паллетизация',
  'logistics-and-handling/fulfilment/de-palletisation': 'Депаллетизация',
  'logistics-and-handling/fulfilment/container-stuffing': 'Наполнение контейнеров',
  'logistics-and-handling/fulfilment/container-destuffing': 'Разгрузка контейнеров',
  'logistics-and-handling/fulfilment/kitting': 'Комплектация',
  'logistics-and-handling/fulfilment/bundling': 'Комплектация',
  'logistics-and-handling/fulfilment/labelling': 'Маркировка',
  'logistics-and-handling/fulfilment/barcoding': 'Штрихкодирование',
  'logistics-and-handling/fulfilment/qr-code-labelling': 'Маркировка QR-кодом',
  'logistics-and-handling/fulfilment/sku-management': 'Управление SKU',
  'logistics-and-handling/fulfilment/batch-management': 'Управление пакетной обработкой',
  'logistics-and-handling/fulfilment/lot-management': 'Управление земельными участками',
  'logistics-and-handling/fulfilment/expiry-date-management': 'Управление сроком годности',
  'logistics-and-handling/fulfilment/returns-management': 'Управление возвратами',
  'logistics-and-handling/fulfilment/reverse-logistics': 'Обратная логистика',
  'logistics-and-handling/fulfilment/quality-check-before-dispatch': 'Проверка качества перед отправкой',
  'logistics-and-handling/fulfilment/repacking': 'Переупаковка',
  'logistics-and-handling/fulfilment/subscription-box-fulfilment': 'Выполнение заказов по подписке',
  'logistics-and-handling/fulfilment/sample-fulfilment': 'Выполнение образцов',
  'logistics-and-handling/fulfilment/promotional-kit-fulfilment': 'Комплектация рекламного набора',
  'logistics-and-handling/fulfilment/export-order-fulfilment': 'Выполнение экспортных заказов',
  'logistics-and-handling/fulfilment/import-order-handling': 'Обработка импортных заказов',
  'logistics-and-handling/fulfilment/temperature-controlled-fulfilment': 'Выполнение заказов с регулируемой температурой',
  'logistics-and-handling/fulfilment/food-fulfilment': 'Выполнение заказов на продукты питания',
  'logistics-and-handling/fulfilment/agricultural-product-fulfilment': 'Выполнение заказов на сельскохозяйственную продукцию',
  'logistics-and-handling/warehousing/food-grade-warehousing': 'Складское хранение пищевых продуктов',
  'logistics-and-handling/warehousing/agricultural-warehousing': 'Сельскохозяйственное складирование',
  'logistics-and-handling/warehousing/customs-bonded-storage': 'Таможенное хранение',
  'logistics-and-handling/warehousing/rack-storage': 'Стеллажные системы хранения',
  'logistics-and-handling/warehousing/raw-material-storage': 'Хранение сырья',
  'logistics-and-handling/warehousing/finished-goods-storage': 'Склад готовой продукции',
  'logistics-and-handling/warehousing/fmcg-warehousing': 'Складирование товаров повседневного спроса',
  'logistics-and-handling/warehousing/e-commerce-warehousing': 'Складирование для электронной коммерции',
  'logistics-and-handling/warehousing/hazard-sensitive-storage': 'Хранение опасных материалов',
  'logistics-and-handling/warehousing/temperature-monitoring': 'Контроль температуры',
  'logistics-and-handling/warehousing/humidity-controlled-storage': 'Хранение с регулируемой влажностью',
  'logistics-and-handling/warehousing/warehouse-inventory-audit': 'Аудит складских запасов',
  'logistics-and-handling/packing/primary-packing/product-packing': 'Упаковка продукции',
  'logistics-and-handling/packing/primary-packing/food-packing': 'Упаковка продуктов питания',
  'logistics-and-handling/packing/primary-packing/agricultural-product-packing': 'Упаковка сельскохозяйственной продукции',
  'logistics-and-handling/packing/primary-packing/retail-packing': 'Розничная упаковка',
  'logistics-and-handling/packing/primary-packing/export-packing': 'Экспортная упаковка',
  'logistics-and-handling/packing/primary-packing/industrial-packing': 'Промышленная упаковка',
  'logistics-and-handling/packing/primary-packing/bulk-packing': 'Упаковка навалом',
  'logistics-and-handling/packing/packaging-types/pouch-packing': 'Упаковка в пакеты',
  'logistics-and-handling/packing/packaging-types/vacuum-packing': 'Вакуумная упаковка',
  'logistics-and-handling/packing/packaging-types/modified-atmosphere-packing': 'Упаковка в модифицированной атмосфере',
  'logistics-and-handling/packing/packaging-types/shrink-wrapping': 'Термоусадочная упаковка',
  'logistics-and-handling/packing/packaging-types/stretch-wrapping': 'Стретч-пленка',
  'logistics-and-handling/packing/packaging-types/carton-packing': 'Картонная упаковка',
  'logistics-and-handling/packing/packaging-types/box-packing': 'Упаковка в коробки',
  'logistics-and-handling/packing/packaging-types/bag-packing': 'Упаковка в пакеты',
  'logistics-and-handling/packing/packaging-types/sack-packing': 'Упаковка в мешки',
  'logistics-and-handling/packing/packaging-types/jute-bag-packing': 'Упаковка в джутовые мешки',
  'logistics-and-handling/packing/packaging-types/paper-bag-packing': 'Упаковка в бумажные пакеты',
  'logistics-and-handling/packing/packaging-types/plastic-bag-packing': 'Упаковка в пластиковые пакеты',
  'logistics-and-handling/packing/packaging-types/tin-packing': 'Жестяная упаковка',
  'logistics-and-handling/packing/packaging-types/jar-packing': 'Упаковка в банки',
  'logistics-and-handling/packing/packaging-types/bottle-packing': 'Упаковка бутылок',
  'logistics-and-handling/packing/packaging-types/can-packing': 'Упаковка банок',
  'logistics-and-handling/packing/packaging-types/drum-packing': 'Упаковка в бочки',
  'logistics-and-handling/packing/packaging-types/barrel-packing': 'Упаковка бочек',
  'logistics-and-handling/packing/packaging-types/pallet-packing': 'Упаковка паллет',
  'logistics-and-handling/packing/packaging-types/crate-packing': 'Упаковка в ящики',
  'logistics-and-handling/packing/packaging-types/wooden-box-packing': 'Упаковка в деревянный ящик',
  'logistics-and-handling/packing/packaging-types/container-packing': 'Упаковка контейнеров',
  'logistics-and-handling/packing/special-packing/private-label-packing': 'Упаковка под собственной торговой маркой',
  'logistics-and-handling/packing/special-packing/white-label-packing': 'Упаковка под чужой торговой маркой',
  'logistics-and-handling/packing/special-packing/retail-ready-packaging': 'Упаковка, готовая к розничной продаже',
  'logistics-and-handling/packing/special-packing/gift-packaging': 'Подарочная упаковка',
  'logistics-and-handling/packing/special-packing/premium-packaging': 'Премиум-упаковка',
  'logistics-and-handling/packing/special-packing/export-standard-packaging': 'Экспортная стандартная упаковка',
  'logistics-and-handling/packing/special-packing/food-grade-packaging': 'Упаковка пищевого качества',
  'logistics-and-handling/packing/special-packing/moisture-proof-packaging': 'Влагостойкая упаковка',
  'logistics-and-handling/packing/special-packing/tamper-evident-packaging': 'Упаковка с защитой от вскрытия',
  'logistics-and-handling/packing/special-packing/temperature-controlled-packaging': 'Упаковка с регулируемой температурой',
  'logistics-and-handling/packing/special-packing/fragile-product-packaging': 'Хрупкая упаковка товара',
  'logistics-and-handling/packing/packing-support/weighing': 'Взвешивание',
  'logistics-and-handling/packing/packing-support/filling': 'Наполнение',
  'logistics-and-handling/packing/packing-support/sealing': 'Герметизация',
  'logistics-and-handling/packing/packing-support/coding': 'Программирование',
  'logistics-and-handling/packing/packing-support/batch-printing': 'Пакетная печать',
  'logistics-and-handling/packing/packing-support/date-printing': 'Печать даты',
  'logistics-and-handling/packing/packing-support/barcode-printing': 'Печать штрихкодов',
  'logistics-and-handling/packing/packing-support/qr-code-printing': 'Печать QR-кодов',
  'logistics-and-handling/packing/packing-support/labelling': 'Маркировка',
  'logistics-and-handling/packing/packing-support/relabelling': 'Переименование',
  'logistics-and-handling/packing/packing-support/stickering': 'Наклейки',
  'logistics-and-handling/packing/packing-support/product-inserts': 'Вкладыши к продукции',
  'logistics-and-handling/packing/packing-support/packaging-inspection': 'Проверка упаковки',
  'logistics-and-handling/packing/packing-support/repacking': 'Переупаковка',
  'logistics-and-handling/packing/packing-support/packaging-material-sourcing': 'Поиск поставщиков упаковочных материалов',
  'logistics-and-handling/packing/packing-support/custom-packaging-design': 'Индивидуальный дизайн упаковки',
  'logistics-and-handling/transportation/road-transport/interstate-transport': 'Межгосударственные перевозки',
  'logistics-and-handling/transportation/road-transport/full-truck-load-ftl': 'Полная загрузка грузовика — FTL',
  'logistics-and-handling/transportation/road-transport/less-than-truck-load-ltl': 'Сборные грузы (LTL)',
  'logistics-and-handling/transportation/road-transport/part-load': 'Частичная загрузка',
  'logistics-and-handling/transportation/road-transport/refrigerated-truck-transport': 'Рефрижераторные перевозки',
  'logistics-and-handling/transportation/road-transport/agricultural-produce-transport': 'Транспортировка сельскохозяйственной продукции',
  'logistics-and-handling/transportation/road-transport/bulk-cargo-transport': 'Перевозка насыпных грузов',
  'logistics-and-handling/transportation/international-transport/international-road-freight': 'Международные автомобильные грузоперевозки',
  'logistics-and-handling/transportation/shipping-types/fcl-full-container-load': 'FCL — Полная загрузка контейнера',
  'logistics-and-handling/transportation/shipping-types/lcl-less-container-load': 'LCL — сборная контейнерная загрузка',
  'logistics-and-handling/transportation/shipping-types/reefer-container': 'Рефрижераторный контейнер',
  'logistics-and-handling/transportation/shipping-types/dry-container': 'Сухой контейнер',
  'logistics-and-handling/transportation/shipping-types/open-top-container': 'Контейнер с открытым верхом',
  'logistics-and-handling/transportation/shipping-types/flat-rack-container': 'Контейнер-платформа',
  'logistics-and-handling/transportation/shipping-types/bulk-cargo': 'Насыпные грузы',
  'logistics-and-handling/transportation/shipping-types/break-bulk-cargo': 'Штучные грузы',
  'logistics-and-handling/transportation/last-mile/same-day-delivery': 'Доставка в тот же день',
  'logistics-and-handling/transportation/last-mile/scheduled-delivery': 'Плановая доставка',
  'logistics-and-handling/transportation/last-mile/b2b-delivery': 'Доставка B2B',
  'logistics-and-handling/transportation/last-mile/b2c-delivery': 'Доставка B2C',
  'logistics-and-handling/transportation/last-mile/hyperlocal-delivery': 'Гиперлокальная доставка',
  'logistics-and-handling/freight-forwarding/domestic-freight-forwarding': 'Экспедирование внутренних грузоперевозок',
  'logistics-and-handling/freight-forwarding/international-freight-forwarding': 'Международные грузоперевозки',
  'logistics-and-handling/freight-forwarding/air-freight-forwarding': 'Экспедирование авиагрузов',
  'logistics-and-handling/freight-forwarding/sea-freight-forwarding': 'Экспедирование морских грузов',
  'logistics-and-handling/freight-forwarding/road-freight-forwarding': 'Автомобильные грузоперевозки',
  'logistics-and-handling/freight-forwarding/rail-freight-forwarding': 'Экспедирование железнодорожных грузоперевозок',
  'logistics-and-handling/freight-forwarding/multimodal-freight': 'Мультимодальные грузоперевозки',
  'logistics-and-handling/freight-forwarding/fcl-forwarding': 'Экспедирование FCL',
  'logistics-and-handling/freight-forwarding/lcl-forwarding': 'Экспедирование сборных грузов (LCL)',
  'logistics-and-handling/freight-forwarding/reefer-freight': 'Рефрижераторные грузы',
  'logistics-and-handling/freight-forwarding/project-cargo': 'Проектный груз',
  'logistics-and-handling/freight-forwarding/door-to-door-freight': 'Доставка грузов от двери до двери',
  'logistics-and-handling/freight-forwarding/port-to-port-freight': 'Грузоперевозки из порта в порт',
  'logistics-and-handling/freight-forwarding/airport-to-airport-freight': 'Грузоперевозки из аэропорта в аэропорт',
  'logistics-and-handling/freight-forwarding/door-to-port-freight': 'Грузоперевозки от двери до порта',
  'logistics-and-handling/freight-forwarding/freight-consolidation': 'Консолидация грузов',
  'logistics-and-handling/freight-forwarding/cargo-consolidation': 'Консолидация грузов',
  'logistics-and-handling/freight-forwarding/freight-documentation': 'Документация на грузоперевозки',
  'logistics-and-handling/freight-forwarding/shipment-tracking': 'Отслеживание отправлений',
  'logistics-and-handling/freight-forwarding/freight-insurance-assistance': 'Помощь в оформлении страхования грузоперевозок',
  'processing': 'Обработка',
  'processing/sorting-and-grading/sorting/shape-sorting': 'Сортировка по форме',
  'processing/sorting-and-grading/sorting/defect-sorting': 'Сортировка дефектов',
  'processing/sorting-and-grading/sorting/foreign-material-removal': 'Удаление посторонних предметов',
  'processing/sorting-and-grading/grading/colour-grading': 'Цветокоррекция',
  'processing/sorting-and-grading/grading/weight-grading': 'Классификация по весу',
  'processing/sorting-and-grading/grading/export-grade-classification': 'Классификация экспортных сортов',
  'processing/sorting-and-grading/grading/premium-grade-selection': 'Отбор премиум-класса',
  'processing/sorting-and-grading/grading/commercial-grade-selection': 'Выбор коммерческого класса',
  'processing/sorting-and-grading/additional/cleaning': 'Уборка',
  'processing/sorting-and-grading/additional/screening': 'Скрининг',
  'processing/sorting-and-grading/additional/sieving': 'Просеивание',
  'processing/sorting-and-grading/additional/de-stoning': 'Удаление камней',
  'processing/sorting-and-grading/additional/de-dusting': 'Удаление пыли',
  'processing/sorting-and-grading/additional/foreign-material-removal': 'Удаление посторонних предметов',
  'processing/sorting-and-grading/additional/metal-detection': 'Обнаружение металла',
  'processing/sorting-and-grading/additional/quality-inspection': 'Контроль качества',
  'processing/cleaning/air-cleaning': 'Очистка воздуха',
  'processing/cleaning/brush-cleaning': 'Чистка кистей',
  'processing/cleaning/mud-removal': 'Удаление грязи',
  'processing/cleaning/stone-removal': 'Удаление камней',
  'processing/cleaning/foreign-matter-removal': 'Удаление посторонних примесей',
  'processing/cleaning/sanitisation': 'Санитарная обработка',
  'processing/cleaning/food-safe-cleaning': 'Безопасная для пищевых продуктов очистка',
  'processing/roasting/roasting-types/continuous-roasting': 'Непрерывная обжарка',
  'processing/roasting/product-specific/cashew-roasting': 'Обжаривание кешью',
  'processing/roasting/product-specific/pistachio-roasting': 'Обжаривание фисташек',
  'processing/roasting/product-specific/seed-roasting': 'Обжарка семян',
  'processing/roasting/product-specific/grain-roasting': 'Обжарка зерна',
  'processing/roasting/additional/custom-roast-profile': 'Пользовательский профиль обжарки',
  'processing/roasting/additional/contract-roasting': 'Контрактная обжарка',
  'processing/roasting/additional/private-label-roasting': 'Обжарка кофе под собственной торговой маркой',
  'processing/roasting/additional/bulk-roasting': 'Массовая обжарка',
  'processing/roasting-and-salting/dry-salted': 'Сухая соль',
  'processing/roasting-and-salting/oil-roasted-and-salted': 'Обжаренные в масле и посоленные',
  'processing/roasting-and-salting/light-salt': 'Светлая соль',
  'processing/roasting-and-salting/medium-salt': 'Средняя соль',
  'processing/roasting-and-salting/extra-salt': 'Дополнительная соль',
  'processing/roasting-and-salting/sea-salt': 'Морская соль',
  'processing/roasting-and-salting/rock-salt': 'Каменная соль',
  'processing/roasting-and-salting/flavoured-salt': 'Ароматизированная соль',
  'processing/roasting-and-salting/seasoned-roasting': 'Жарка с приправами',
  'processing/roasting-and-salting/masala-roasting': 'Жарка масала',
  'processing/roasting-and-salting/chilli-roasting': 'Жарение чили',
  'processing/roasting-and-salting/pepper-roasting': 'Жарение перца',
  'processing/roasting-and-salting/honey-roasting': 'Обжаривание меда',
  'processing/roasting-and-salting/sweet-and-salted': 'Сладкий и соленый',
  'processing/roasting-and-salting/custom-seasoning': 'Приправы на заказ',
  'processing/cutting-chopping/cubing': 'Кубирование',
  'processing/cutting-chopping/julienne-cutting': 'Жюльен Каттинг',
  'processing/cutting-chopping/fine-chopping': 'Мелкая нарезка',
  'processing/cutting-chopping/rough-chopping': 'Грубая рубка',
  'processing/cutting-chopping/strip-cutting': 'Нарезка полос',
  'processing/cutting-chopping/ring-cutting': 'Нарезка колец',
  'processing/cutting-chopping/quartering': 'Квартирирование',
  'processing/cutting-chopping/custom-size-cutting': 'Изготовление по индивидуальным размерам',
  'processing/cutting-chopping/vegetable-cutting': 'Нарезка овощей',
  'processing/cutting-chopping/fruit-cutting': 'Нарезка фруктов',
  'processing/cutting-chopping/nut-chopping': 'Измельчение орехов',
  'processing/cutting-chopping/herb-chopping': 'Измельчение зелени',
  'processing/blanching/hot-water-blanching': 'Бланширование горячей водой',
  'processing/blanching/continuous-blanching': 'Непрерывное бланширование',
  'processing/blanching/batch-blanching': 'Партионное бланширование',
  'processing/blanching/vegetable-blanching': 'Бланширование овощей',
  'processing/blanching/nut-blanching': 'Бланширование орехов',
  'processing/blanching/almond-blanching': 'Бланширование миндаля',
  'processing/blanching/peanut-blanching': 'Бланширование арахиса',
  'processing/blanching/fruit-blanching': 'Бланширование фруктов',
  'processing/blanching/custom-temperature-blanching': 'Бланширование при заданной температуре',
  'processing/blanching/custom-time-blanching': 'Индивидуальное обесцвечивание времени',
  'processing/pitting/fruit-pitting': 'Выкапывание косточек из фруктов',
  'processing/pitting/date-pitting': 'Финиковая ямка',
  'processing/pitting/olive-pitting': 'Выкапывание оливок',
  'processing/pitting/cherry-pitting': 'Удаление косточек из вишни',
  'processing/pitting/apricot-pitting': 'Удаление косточек из абрикоса',
  'processing/pitting/peach-pitting': 'Удаление косточек из персиков',
  'processing/pitting/plum-pitting': 'Удаление косточек из сливы',
  'processing/pitting/manual-pitting': 'Ручная питтинговая обработка',
  'processing/pitting/machine-pitting': 'Машинная ямка',
  'processing/pitting/bulk-pitting': 'Массовая ямочная очистка',
  'processing/pitting/custom-pitting': 'Индивидуальная пит-стоп-зона',
  'processing/peeling/chemical-peeling': 'Химический пилинг',
  'processing/peeling/dry-peeling': 'Сухое шелушение',
  'processing/peeling/wet-peeling': 'Влажное отшелушивание',
  'processing/peeling/nut-peeling': 'Очистка орехов',
  'processing/peeling/fruit-peeling': 'Очистка фруктов',
  'processing/peeling/vegetable-peeling': 'Очистка овощей',
  'processing/peeling/almond-skin-removal': 'Удаление кожуры миндаля',
  'processing/peeling/peanut-skin-removal': 'Удаление кожуры арахиса',
  'processing/shelling/nut-shelling': 'Очистка орехов от скорлупы',
  'processing/shelling/cashew-shelling': 'Очистка кешью от скорлупы',
  'processing/shelling/almond-shelling': 'Очистка миндаля от скорлупы',
  'processing/shelling/peanut-shelling': 'Очистка арахиса от скорлупы',
  'processing/shelling/pistachio-shelling': 'Очистка фисташек от скорлупы',
  'processing/shelling/walnut-shelling': 'Очистка грецких орехов от скорлупы',
  'processing/shelling/seed-shelling': 'Очистка семян от скорлупы',
  'processing/shelling/manual-shelling': 'Ручной обстрел',
  'processing/shelling/machine-shelling': 'Автоматический обстрел',
  'processing/shelling/cracking': 'Взлом',
  'processing/shelling/kernel-separation': 'Разделение ядер',
  'processing/drying/tray-drying': 'Сушка в лотках',
  'processing/drying/tunnel-drying': 'Туннельная сушка',
  'processing/drying/drum-drying': 'Сушка в барабане',
  'processing/drying/dehydration': 'Обезвоживание',
  'processing/drying/low-temperature-drying': 'Низкотемпературная сушка',
  'processing/drying/fruit-drying': 'Сушка фруктов',
  'processing/drying/vegetable-drying': 'Сушка овощей',
  'processing/drying/herb-drying': 'Сушка трав',
  'processing/drying/spice-drying': 'Сушка специй',
  'processing/drying/nut-drying': 'Сушка орехов',
  'processing/freezing-iqf/standard-freezing': 'Стандартная заморозка',
  'processing/freezing-iqf/iqf-individual-quick-freezing': 'IQF — Индивидуальная быстрая заморозка',
  'processing/freezing-iqf/frozen-storage': 'Замороженное хранилище',
  'processing/freezing-iqf/fruit-freezing': 'Заморозка фруктов',
  'processing/freezing-iqf/vegetable-freezing': 'Заморозка овощей',
  'processing/freezing-iqf/food-freezing': 'Замораживание продуктов',
  'processing/freezing-iqf/pre-freezing': 'Предварительная заморозка',
  'processing/grinding-and-milling/grinding': 'Шлифовка',
  'processing/grinding-and-milling/powdering': 'Порошкообразование',
  'processing/grinding-and-milling/pulverising': 'Измельчение',
  'processing/grinding-and-milling/milling': 'Помол',
  'processing/grinding-and-milling/grain-milling': 'Помол зерна',
  'processing/grinding-and-milling/nut-grinding': 'Измельчение орехов',
  'processing/grinding-and-milling/seed-grinding': 'Измельчение семян',
  'processing/grinding-and-milling/custom-mesh-size-grinding': 'Шлифовка с нестандартным размером сетки',
  'processing/crushing/fruit-crushing': 'Измельчение фруктов',
  'processing/crushing/seed-crushing': 'Измельчение семян',
  'processing/crushing/nut-crushing': 'Измельчение орехов',
  'processing/crushing/spice-crushing': 'Измельчение специй',
  'processing/crushing/grain-crushing': 'Дробление зерна',
  'processing/crushing/coarse-crushing': 'грубое дробление',
  'processing/crushing/fine-crushing': 'Тонкое дробление',
  'processing/crushing/industrial-crushing': 'Промышленное дробление',
  'processing/mixing-and-blending/ingredient-mixing': 'Смешивание ингредиентов',
  'processing/mixing-and-blending/wet-blending': 'Влажное смешивание',
  'processing/mixing-and-blending/powder-blending': 'Смешивание порошков',
  'processing/mixing-and-blending/seasoning-blending': 'Смешивание приправ',
  'processing/mixing-and-blending/nut-mixing': 'Смешивание орехов',
  'processing/mixing-and-blending/grain-mixing': 'Смешивание зерна',
  'processing/mixing-and-blending/custom-recipe-blending': 'Смешивание ингредиентов по индивидуальному рецепту',
  'processing/mixing-and-blending/contract-blending': 'Контрактное смешивание',
  'processing/seasoning/salt-seasoning': 'Соль и приправа',
  'processing/seasoning/spice-seasoning': 'Специи для приправы',
  'processing/seasoning/masala-coating': 'Масала-покрытие',
  'processing/seasoning/chilli-coating': 'Покрытие из перца чили',
  'processing/seasoning/pepper-coating': 'Перечная посыпка',
  'processing/seasoning/cheese-flavouring': 'Сырный ароматизатор',
  'processing/seasoning/bbq-flavouring': 'Ароматизатор барбекю',
  'processing/seasoning/sweet-coating': 'Сладкая глазурь',
  'processing/seasoning/honey-coating': 'Медовое покрытие',
  'processing/seasoning/chocolate-coating': 'Шоколадная глазурь',
  'processing/seasoning/custom-flavouring': 'Индивидуальный вкус',
  'processing/seasoning/private-label-flavouring': 'Ароматизаторы под собственной торговой маркой',
  'processing/cooking-heat-treatment/deep-frying': 'Жарка во фритюре',
  'processing/cooking-heat-treatment/air-frying': 'Жарка во фритюре',
  'processing/cooking-heat-treatment/roasting': 'Обжаривание',
  'processing/cooking-heat-treatment/heat-treatment': 'Термическая обработка',
  'processing/cooking-heat-treatment/steam-treatment': 'Обработка паром',
  'processing/cooking-heat-treatment/precooking': 'Предварительное приготовление',
  'processing/extraction/fruit-pulping': 'Измельчение фруктовой мякоти',
  'processing/extraction/vegetable-pulping': 'Измельчение овощей',
  'processing/extraction/puree-production': 'Производство пюре',
  'processing/extraction/concentrate-production': 'Производство концентратов',
  'processing/extraction/seed-oil-extraction': 'Извлечение масла из семян',
  'processing/extraction/essential-oil-extraction': 'Экстракция эфирных масел',
  'processing/extraction/clarification': 'Уточнение',
  'processing/quality-testing/size-testing': 'Тестирование размеров',
  'processing/quality-testing/colour-testing': 'Тестирование цвета',
  'processing/quality-testing/foreign-matter-inspection': 'Проверка на наличие посторонних примесей',
  'processing/quality-testing/residue-testing': 'Анализ остаточных веществ',
  'processing/quality-testing/product-sampling': 'Отбор проб продукции',
  'processing/quality-testing/batch-testing': 'Пакетное тестирование',
  'processing/quality-testing/export-quality-inspection': 'Контроль качества при экспорте',
};
