/**
 * Russian labels for service taxonomy nodes, keyed by slug.
 *
 * DELIBERATELY PARTIAL. Only translations we are confident are the term a
 * Russian trader would actually use are here; anything uncertain is omitted, and
 * the seed reports it in `missing-ru-translations.txt` so a native speaker can
 * fill it in. Shipping invented Russian to a Russian client is worse than
 * shipping English, and an untranslated leaf still reads fine next to a
 * translated section heading.
 *
 * Covered here: every structural node (the 3 sections, 36 groups, and the
 * subgroup/country levels) plus the leaves whose Russian is unambiguous. Those
 * structural nodes are what the browse UI shows before any drill-down, so they
 * are the ones worth getting right first.
 */
export const SERVICE_TAXONOMY_RU: Record<string, string> = {
  // ── sections ────────────────────────────────────────────────────
  'financial-and-compliance': 'Финансы и соответствие требованиям',
  'logistics-and-handling': 'Логистика и обработка',
  processing: 'Переработка',

  // ── financial & compliance ──────────────────────────────────────
  'financial-and-compliance/accounting': 'Бухгалтерский учёт',
  'financial-and-compliance/accounting/india': 'Индия',
  'financial-and-compliance/accounting/russia': 'Россия',
  'financial-and-compliance/accounting/international': 'Международный / трансграничный',
  'financial-and-compliance/taxation': 'Налогообложение',
  'financial-and-compliance/customs-clearance': 'Таможенное оформление',
  'financial-and-compliance/financial-services': 'Финансовые услуги',
  'financial-and-compliance/audit-and-certification': 'Аудит и сертификация',
  'financial-and-compliance/insurance': 'Страхование',

  // ── logistics & handling ────────────────────────────────────────
  'logistics-and-handling/customs-and-border-logistics': 'Таможенная и приграничная логистика',
  'logistics-and-handling/customs-and-border-logistics/india': 'Индия',
  'logistics-and-handling/customs-and-border-logistics/russia': 'Россия',
  'logistics-and-handling/customs-and-border-logistics/international': 'Международное',
  'logistics-and-handling/fulfilment': 'Фулфилмент',
  'logistics-and-handling/warehousing': 'Складские услуги',
  'logistics-and-handling/packing': 'Упаковка',
  'logistics-and-handling/packing/primary-packing': 'Первичная упаковка',
  'logistics-and-handling/packing/packaging-types': 'Виды упаковки',
  'logistics-and-handling/packing/special-packing': 'Специальная упаковка',
  'logistics-and-handling/packing/packing-support': 'Сопровождение упаковки',
  'logistics-and-handling/transportation': 'Перевозки',
  'logistics-and-handling/transportation/road-transport': 'Автомобильные перевозки',
  'logistics-and-handling/transportation/international-transport': 'Международные перевозки',
  'logistics-and-handling/transportation/shipping-types': 'Типы отправок',
  'logistics-and-handling/transportation/last-mile': 'Последняя миля',
  'logistics-and-handling/freight-forwarding': 'Экспедирование грузов',
  'logistics-and-handling/cold-chain': 'Холодовая цепь',
  'logistics-and-handling/loading-and-unloading': 'Погрузка и разгрузка',
  'logistics-and-handling/container-handling': 'Обработка контейнеров',
  'logistics-and-handling/last-mile-delivery': 'Доставка последней мили',
  'logistics-and-handling/inspection': 'Инспекция',

  // ── processing ──────────────────────────────────────────────────
  'processing/sorting-and-grading': 'Сортировка и калибровка',
  'processing/sorting-and-grading/sorting': 'Сортировка',
  'processing/sorting-and-grading/grading': 'Калибровка',
  'processing/sorting-and-grading/additional': 'Дополнительно',
  'processing/cleaning': 'Очистка',
  'processing/roasting': 'Обжарка',
  'processing/roasting/roasting-types': 'Виды обжарки',
  'processing/roasting/product-specific': 'По продукту',
  'processing/roasting/additional': 'Дополнительно',
  'processing/roasting-and-salting': 'Обжарка и посол',
  'processing/cutting-chopping': 'Резка / измельчение',
  'processing/blanching': 'Бланширование',
  'processing/pitting': 'Удаление косточек',
  'processing/peeling': 'Очистка от кожуры',
  'processing/shelling': 'Лущение / очистка от скорлупы',
  'processing/drying': 'Сушка',
  'processing/freezing-iqf': 'Заморозка / IQF',
  'processing/grinding-and-milling': 'Измельчение и помол',
  'processing/crushing': 'Дробление',
  'processing/mixing-and-blending': 'Смешивание и купажирование',
  'processing/seasoning': 'Приправы и ароматизация',
  'processing/cooking-heat-treatment': 'Варка / термообработка',
  'processing/extraction': 'Экстракция',
  'processing/quality-testing': 'Контроль качества',
  'processing/packaging': 'Фасовка',

  // ── leaves with unambiguous Russian ─────────────────────────────
  // Accounting (shared terms across the three country branches).
  'financial-and-compliance/accounting/india/bookkeeping': 'Ведение бухгалтерского учёта',
  'financial-and-compliance/accounting/russia/bookkeeping': 'Ведение бухгалтерского учёта',
  'financial-and-compliance/accounting/russia/vat-accounting': 'Учёт НДС',
  'financial-and-compliance/accounting/russia/vat-return-preparation': 'Подготовка декларации по НДС',
  'financial-and-compliance/accounting/russia/tax-accounting': 'Налоговый учёт',
  'financial-and-compliance/accounting/russia/payroll-accounting': 'Расчёт заработной платы',
  'financial-and-compliance/accounting/russia/financial-statements': 'Финансовая отчётность',
  'financial-and-compliance/accounting/russia/accounts-payable': 'Кредиторская задолженность',
  'financial-and-compliance/accounting/russia/accounts-receivable': 'Дебиторская задолженность',
  'financial-and-compliance/accounting/russia/bank-reconciliation': 'Банковская сверка',
  'financial-and-compliance/accounting/russia/inventory-accounting': 'Учёт запасов',
  'financial-and-compliance/accounting/russia/fixed-asset-accounting': 'Учёт основных средств',
  'financial-and-compliance/accounting/russia/tax-reporting': 'Налоговая отчётность',
  'financial-and-compliance/accounting/india/payroll-accounting': 'Расчёт заработной платы',
  'financial-and-compliance/accounting/india/bank-reconciliation': 'Банковская сверка',
  'financial-and-compliance/accounting/india/inventory-accounting': 'Учёт запасов',
  'financial-and-compliance/accounting/india/cost-accounting': 'Учёт затрат',
  'financial-and-compliance/accounting/international/ifrs-accounting': 'Учёт по МСФО',
  'financial-and-compliance/accounting/international/payroll-accounting': 'Расчёт заработной платы',
  'financial-and-compliance/accounting/international/accounts-payable': 'Кредиторская задолженность',
  'financial-and-compliance/accounting/international/accounts-receivable': 'Дебиторская задолженность',

  // Warehousing / cold storage — standard trade terms.
  'logistics-and-handling/warehousing/general-warehousing': 'Общее складское хранение',
  'logistics-and-handling/warehousing/cold-storage': 'Холодильное хранение',
  'logistics-and-handling/warehousing/frozen-storage': 'Хранение в морозильной камере',
  'logistics-and-handling/warehousing/chilled-storage': 'Охлаждаемое хранение',
  'logistics-and-handling/warehousing/ambient-storage': 'Хранение при температуре окружающей среды',
  'logistics-and-handling/warehousing/bonded-warehousing': 'Таможенный склад',
  'logistics-and-handling/warehousing/bulk-storage': 'Хранение навалом',
  'logistics-and-handling/warehousing/pallet-storage': 'Паллетное хранение',
  'logistics-and-handling/warehousing/container-storage': 'Хранение контейнеров',
  'logistics-and-handling/warehousing/long-term-storage': 'Долгосрочное хранение',
  'logistics-and-handling/warehousing/temporary-storage': 'Временное хранение',

  // Transport / freight.
  'logistics-and-handling/transportation/road-transport/local-transport': 'Местные перевозки',
  'logistics-and-handling/transportation/road-transport/intercity-transport': 'Междугородние перевозки',
  'logistics-and-handling/transportation/road-transport/container-transport': 'Контейнерные перевозки',
  'logistics-and-handling/transportation/international-transport/air-freight': 'Авиаперевозки',
  'logistics-and-handling/transportation/international-transport/sea-freight': 'Морские перевозки',
  'logistics-and-handling/transportation/international-transport/rail-freight': 'Железнодорожные перевозки',
  'logistics-and-handling/transportation/international-transport/multimodal-transport': 'Мультимодальные перевозки',
  'logistics-and-handling/transportation/last-mile/last-mile-delivery': 'Доставка последней мили',
  'logistics-and-handling/transportation/last-mile/express-delivery': 'Экспресс-доставка',

  // Customs.
  'logistics-and-handling/customs-and-border-logistics/import-customs-clearance': 'Таможенное оформление импорта',
  'logistics-and-handling/customs-and-border-logistics/export-customs-clearance': 'Таможенное оформление экспорта',
  'logistics-and-handling/customs-and-border-logistics/customs-documentation': 'Таможенная документация',
  'logistics-and-handling/customs-and-border-logistics/customs-brokerage': 'Услуги таможенного брокера',
  'logistics-and-handling/customs-and-border-logistics/import-documentation': 'Импортная документация',
  'logistics-and-handling/customs-and-border-logistics/export-documentation': 'Экспортная документация',
  'logistics-and-handling/customs-and-border-logistics/russia/russian-customs': 'Российская таможня',
  'logistics-and-handling/customs-and-border-logistics/india/indian-customs': 'Индийская таможня',

  // Processing leaves.
  'processing/sorting-and-grading/sorting/manual-sorting': 'Ручная сортировка',
  'processing/sorting-and-grading/sorting/machine-sorting': 'Машинная сортировка',
  'processing/sorting-and-grading/sorting/optical-sorting': 'Оптическая сортировка',
  'processing/sorting-and-grading/sorting/colour-sorting': 'Сортировка по цвету',
  'processing/sorting-and-grading/sorting/size-sorting': 'Сортировка по размеру',
  'processing/sorting-and-grading/sorting/weight-sorting': 'Сортировка по весу',
  'processing/sorting-and-grading/grading/quality-grading': 'Калибровка по качеству',
  'processing/sorting-and-grading/grading/size-grading': 'Калибровка по размеру',
  'processing/sorting-and-grading/grading/moisture-grading': 'Калибровка по влажности',
  'processing/cleaning/dry-cleaning': 'Сухая очистка',
  'processing/cleaning/wet-cleaning': 'Влажная очистка',
  'processing/cleaning/water-washing': 'Промывка водой',
  'processing/cleaning/steam-cleaning': 'Паровая очистка',
  'processing/cleaning/dust-removal': 'Удаление пыли',
  'processing/roasting/roasting-types/dry-roasting': 'Сухая обжарка',
  'processing/roasting/roasting-types/oil-roasting': 'Обжарка в масле',
  'processing/roasting/roasting-types/hot-air-roasting': 'Обжарка горячим воздухом',
  'processing/roasting/roasting-types/drum-roasting': 'Барабанная обжарка',
  'processing/roasting/roasting-types/batch-roasting': 'Партионная обжарка',
  'processing/roasting/roasting-types/light-roasting': 'Светлая обжарка',
  'processing/roasting/roasting-types/medium-roasting': 'Средняя обжарка',
  'processing/roasting/roasting-types/dark-roasting': 'Тёмная обжарка',
  'processing/roasting/product-specific/nut-roasting': 'Обжарка орехов',
  'processing/roasting/product-specific/coffee-roasting': 'Обжарка кофе',
  'processing/roasting/product-specific/almond-roasting': 'Обжарка миндаля',
  'processing/roasting/product-specific/peanut-roasting': 'Обжарка арахиса',
  'processing/roasting/product-specific/spice-roasting': 'Обжарка специй',
  'processing/cutting-chopping/hand-cutting': 'Ручная резка',
  'processing/cutting-chopping/machine-cutting': 'Машинная резка',
  'processing/cutting-chopping/slicing': 'Нарезка ломтиками',
  'processing/cutting-chopping/dicing': 'Нарезка кубиками',
  'processing/cutting-chopping/shredding': 'Шинковка',
  'processing/cutting-chopping/halving': 'Разрезание пополам',
  'processing/blanching/water-blanching': 'Бланширование в воде',
  'processing/blanching/steam-blanching': 'Бланширование паром',
  'processing/peeling/manual-peeling': 'Ручная очистка',
  'processing/peeling/mechanical-peeling': 'Механическая очистка',
  'processing/peeling/steam-peeling': 'Паровая очистка',
  'processing/drying/sun-drying': 'Солнечная сушка',
  'processing/drying/solar-drying': 'Гелиосушка',
  'processing/drying/hot-air-drying': 'Сушка горячим воздухом',
  'processing/drying/vacuum-drying': 'Вакуумная сушка',
  'processing/drying/freeze-drying': 'Сублимационная сушка',
  'processing/drying/spray-drying': 'Распылительная сушка',
  'processing/freezing-iqf/blast-freezing': 'Шоковая заморозка',
  'processing/freezing-iqf/cryogenic-freezing': 'Криогенная заморозка',
  'processing/freezing-iqf/thawing': 'Размораживание',
  'processing/grinding-and-milling/fine-grinding': 'Тонкий помол',
  'processing/grinding-and-milling/coarse-grinding': 'Крупный помол',
  'processing/grinding-and-milling/flour-milling': 'Мукомольное производство',
  'processing/grinding-and-milling/spice-grinding': 'Помол специй',
  'processing/grinding-and-milling/coffee-grinding': 'Помол кофе',
  'processing/mixing-and-blending/dry-blending': 'Сухое смешивание',
  'processing/mixing-and-blending/spice-blending': 'Купажирование специй',
  'processing/mixing-and-blending/tea-blending': 'Купажирование чая',
  'processing/mixing-and-blending/coffee-blending': 'Купажирование кофе',
  'processing/cooking-heat-treatment/boiling': 'Варка',
  'processing/cooking-heat-treatment/steaming': 'Приготовление на пару',
  'processing/cooking-heat-treatment/baking': 'Выпекание',
  'processing/cooking-heat-treatment/frying': 'Жарка',
  'processing/cooking-heat-treatment/pasteurisation': 'Пастеризация',
  'processing/cooking-heat-treatment/sterilisation': 'Стерилизация',
  'processing/extraction/juice-extraction': 'Отжим сока',
  'processing/extraction/oil-extraction': 'Извлечение масла',
  'processing/extraction/cold-pressing': 'Холодный отжим',
  'processing/extraction/hot-pressing': 'Горячий отжим',
  'processing/extraction/filtering': 'Фильтрация',
  'processing/quality-testing/quality-inspection': 'Инспекция качества',
  'processing/quality-testing/moisture-testing': 'Определение влажности',
  'processing/quality-testing/metal-detection': 'Металлодетекция',
  'processing/quality-testing/x-ray-inspection': 'Рентген-контроль',
  'processing/quality-testing/microbiological-testing': 'Микробиологические исследования',
  'processing/quality-testing/pre-shipment-inspection': 'Предотгрузочная инспекция',

  // legal
  'financial-and-compliance/legal': 'Юридические услуги',
  'financial-and-compliance/legal/india': 'Индия',
  'financial-and-compliance/legal/russia': 'Россия',
  'financial-and-compliance/legal/international': 'Международный / трансграничный',
  'financial-and-compliance/legal/india/sale-and-purchase-agreement-drafting': 'Составление договора купли-продажи',
  'financial-and-compliance/legal/india/contract-review-and-vetting': 'Правовая экспертиза договоров',
  'financial-and-compliance/legal/india/agency-and-distribution-agreements': 'Агентские и дистрибьюторские договоры',
  'financial-and-compliance/legal/india/non-disclosure-agreements': 'Соглашения о неразглашении (NDA)',
  'financial-and-compliance/legal/india/company-incorporation': 'Регистрация компании',
  'financial-and-compliance/legal/india/foreign-subsidiary-setup': 'Создание дочерней компании',
  'financial-and-compliance/legal/india/shareholder-and-joint-venture-agreements': 'Акционерные соглашения и договоры о СП',
  'financial-and-compliance/legal/india/trademark-search-and-filing': 'Поиск и регистрация товарного знака',
  'financial-and-compliance/legal/india/trademark-opposition': 'Возражения против регистрации товарного знака',
  'financial-and-compliance/legal/india/geographical-indication-registration': 'Регистрация географического указания',
  'financial-and-compliance/legal/india/copyright-registration': 'Регистрация авторских прав',
  'financial-and-compliance/legal/india/anti-dumping-and-trade-remedy-advisory': 'Антидемпинговые меры и защита рынка',
  'financial-and-compliance/legal/india/commercial-arbitration': 'Коммерческий арбитраж',
  'financial-and-compliance/legal/india/debt-recovery-and-demand-notices': 'Взыскание задолженности и претензии',
  'financial-and-compliance/legal/india/commercial-litigation': 'Коммерческие судебные споры',
  'financial-and-compliance/legal/india/agricultural-land-due-diligence': 'Проверка сельскохозяйственных земель',
  'financial-and-compliance/legal/india/warehouse-and-cold-store-lease-drafting': 'Договоры аренды склада и холодильника',
  'financial-and-compliance/legal/india/employment-and-contractor-agreements': 'Трудовые и подрядные договоры',
  'financial-and-compliance/legal/india/labour-law-compliance': 'Соблюдение трудового законодательства',
  'financial-and-compliance/legal/india/legal-due-diligence': 'Юридический due diligence',
  'financial-and-compliance/legal/india/power-of-attorney-drafting': 'Составление доверенности',
  'financial-and-compliance/legal/india/apostille-and-document-legalisation': 'Апостиль и легализация документов',
  'financial-and-compliance/legal/india/cargo-insurance-claim-support': 'Сопровождение страховых требований по грузу',
  'financial-and-compliance/legal/russia/supply-contract-drafting': 'Составление договора поставки',
  'financial-and-compliance/legal/russia/contract-review-and-vetting': 'Правовая экспертиза договоров',
  'financial-and-compliance/legal/russia/agency-and-distribution-agreements': 'Агентские и дистрибьюторские договоры',
  'financial-and-compliance/legal/russia/non-disclosure-agreements': 'Соглашения о неразглашении (NDA)',
  'financial-and-compliance/legal/russia/ooo-company-registration': 'Регистрация ООО',
  'financial-and-compliance/legal/russia/individual-entrepreneur-registration': 'Регистрация ИП',
  'financial-and-compliance/legal/russia/representative-office-setup': 'Открытие представительства',
  'financial-and-compliance/legal/russia/charter-and-participant-agreements': 'Устав и договоры участников',
  'financial-and-compliance/legal/russia/egrul-changes-and-filings': 'Внесение изменений в ЕГРЮЛ',
  'financial-and-compliance/legal/russia/rosselkhoznadzor-compliance-advisory': 'Сопровождение требований Россельхознадзора',
  'financial-and-compliance/legal/russia/eaeu-technical-regulation-compliance': 'Соответствие техрегламентам ЕАЭС',
  'financial-and-compliance/legal/russia/declaration-of-conformity-support': 'Оформление декларации о соответствии',
  'financial-and-compliance/legal/russia/trademark-registration-rospatent': 'Регистрация товарного знака (Роспатент)',
  'financial-and-compliance/legal/russia/currency-control-and-repatriation-advisory': 'Валютный контроль и репатриация выручки',
  'financial-and-compliance/legal/russia/customs-classification-opinion-tn-ved': 'Классификация товара по ТН ВЭД',
  'financial-and-compliance/legal/russia/customs-dispute-representation': 'Споры с таможенными органами',
  'financial-and-compliance/legal/russia/sanctions-and-export-control-screening': 'Проверка на санкции и экспортный контроль',
  'financial-and-compliance/legal/russia/arbitrazh-court-representation': 'Представительство в арбитражном суде',
  'financial-and-compliance/legal/russia/commercial-arbitration': 'Коммерческий арбитраж',
  'financial-and-compliance/legal/russia/debt-recovery-and-claim-letters': 'Взыскание задолженности и претензии',
  'financial-and-compliance/legal/russia/bankruptcy-and-insolvency-advisory': 'Банкротство и несостоятельность',
  'financial-and-compliance/legal/russia/land-and-warehouse-lease-drafting': 'Договоры аренды земли и склада',
  'financial-and-compliance/legal/russia/agricultural-land-due-diligence': 'Проверка сельскохозяйственных земель',
  'financial-and-compliance/legal/russia/employment-contracts-and-hr-documents': 'Трудовые договоры и кадровые документы',
  'financial-and-compliance/legal/russia/migrant-worker-documentation': 'Оформление иностранных работников',
  'financial-and-compliance/legal/russia/personal-data-152-fz-compliance': 'Соответствие 152-ФЗ о персональных данных',
  'financial-and-compliance/legal/russia/legal-due-diligence': 'Юридический due diligence',
  'financial-and-compliance/legal/russia/notarisation-and-apostille-support': 'Нотариальное заверение и апостиль',
  'financial-and-compliance/legal/russia/cargo-insurance-claim-support': 'Сопровождение страховых требований по грузу',
  'financial-and-compliance/legal/international/international-sale-contract-drafting': 'Составление международного договора купли-продажи',
  'financial-and-compliance/legal/international/gafta-contract-advisory': 'Консультации по контрактам GAFTA',
  'financial-and-compliance/legal/international/fosfa-contract-advisory': 'Консультации по контрактам FOSFA',
  'financial-and-compliance/legal/international/incoterms-advisory': 'Консультации по Инкотермс',
  'financial-and-compliance/legal/international/cross-border-distribution-and-agency-agreements': 'Трансграничные дистрибьюторские и агентские договоры',
  'financial-and-compliance/legal/international/letter-of-credit-and-ucp-600-advisory': 'Аккредитивы и UCP 600',
  'financial-and-compliance/legal/international/trade-finance-documentation-review': 'Экспертиза документов торгового финансирования',
  'financial-and-compliance/legal/international/sanctions-and-export-control-screening': 'Проверка на санкции и экспортный контроль',
  'financial-and-compliance/legal/international/cross-border-due-diligence': 'Трансграничный due diligence',
  'financial-and-compliance/legal/international/gafta-arbitration-representation': 'Представительство в арбитраже GAFTA',
  'financial-and-compliance/legal/international/icc-arbitration-representation': 'Представительство в арбитраже ICC',
  'financial-and-compliance/legal/international/international-mediation': 'Международная медиация',
  'financial-and-compliance/legal/international/enforcement-of-foreign-awards': 'Признание и исполнение иностранных решений',
  'financial-and-compliance/legal/international/cross-border-debt-recovery': 'Трансграничное взыскание задолженности',
  'financial-and-compliance/legal/international/international-trademark-filing-madrid-protocol': 'Международная регистрация товарного знака (Мадридская система)',
  'financial-and-compliance/legal/international/phytosanitary-and-quarantine-legal-support': 'Правовое сопровождение фитосанитарии и карантина',
  'financial-and-compliance/legal/international/organic-certification-legal-support': 'Правовое сопровождение органической сертификации',
  'financial-and-compliance/legal/international/halal-and-kosher-certification-legal-support': 'Правовое сопровождение сертификации халяль и кошер',
  'financial-and-compliance/legal/international/food-labelling-compliance-review': 'Проверка маркировки пищевой продукции',
  'financial-and-compliance/legal/international/product-liability-and-recall-advisory': 'Ответственность за продукцию и отзыв товара',
  'financial-and-compliance/legal/international/marine-cargo-claim-support': 'Морские грузовые претензии',
  'financial-and-compliance/legal/international/charterparty-and-bill-of-lading-advisory': 'Чартер и коносамент',
  'financial-and-compliance/legal/international/joint-venture-structuring': 'Структурирование совместных предприятий',
  'financial-and-compliance/legal/international/cross-border-tax-structuring-advisory': 'Трансграничное налоговое структурирование',
  'financial-and-compliance/legal/international/data-protection-gdpr-advisory': 'Защита персональных данных (GDPR)',
  'financial-and-compliance/legal/international/legal-retainer-ongoing-advisory': 'Абонентское юридическое обслуживание',
  'financial-and-compliance/legal/international/apostille-and-document-legalisation': 'Апостиль и легализация документов',
  'financial-and-compliance/legal/international/notarisation-support': 'Нотариальное сопровождение',
};
